<?php
  $lang['number']		= 'Referencia';
  $lang['date']			= 'Fecha Facturacion';
  $lang['due']			= 'Facha de vencimiento';
  $lang['to']			= 'Facturacion a';
  $lang['from']			= 'Nuestra informacion ';
  $lang['product']		= 'Curso';
  $lang['qty']			= 'Cantidad';
  $lang['price']		= 'Precio';
  $lang['discount']		= 'Descuento';
  $lang['vat']			= 'Impuestos';
  $lang['total']		= 'Total';
  $lang['page']			= 'Pagina';
  $lang['page_of']		= 'de';
?>